server:
  port: 9999
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JiZhuanMail
    username: root
    password: 123456
